### ISSUE TITLE
Threads não estão sendo criadas

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/diario-de-feira#25]
Apesar de ter a variável KEYWORDS configurada e com valores, palavras-chaves não estão sendo lidas e, por consequência, as threads com temas não estão sendo criadas.

**Comment by luandadantas** [comment]
Bom dia Ana! 
Será que pode ter sido algo no formato do KEYWORDS no env.?
No meu env. local, usei algo assim (tudo juntinho):
`KEYWORDS='{"decretos":["decreto"],"aditivos":["aditivo"],"licitações":["licitação"],"dispensa de licitação":["dispensa de licitação"],"pandemia":["covid", "coronavirus", "pandemia"],"acordo de cooperação":["acordo de cooperação"],"locação de imóvel":["locação de imóvel","aluguel de imóvel"],"extratos":["extrato de"],"inclusão":["inclusão social","inclusão digital","inclusão econômica"],"licença ambiental":["licença ambiental","licença unificada","licença de operação"]}'`
Quando tentei deixar no formato de dicionário, dava problema na hora de ler a variável.
